const products = [
  { id: '001', name: 'Optimals Hydra Radiance Cream', category: 'Face Care', price: 15000, image: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=80', description: 'A comforting daily cream for skin that feels fresh, soft and cared for.', benefits: 'Helps replenish moisture and leaves skin feeling smooth.', usage: 'Apply to clean face and neck morning and evening.', ingredients: 'Ingredients available on product packaging.', availability: 'In Stock', featured: true },
  { id: '002', name: 'Milk & Honey Gold Body Cream', category: 'Body Care', price: 12500, image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=900&q=80', description: 'A rich body cream with a warm, comforting feel for everyday softness.', benefits: 'Nourishes dry-feeling skin and helps lock in moisture.', usage: 'Massage generously into the body after bathing.', ingredients: 'Ingredients available on product packaging.', availability: 'In Stock', featured: true },
  { id: '003', name: 'NovAge Skinrelief Serum', category: 'Skincare', price: 22000, image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80', description: 'A lightweight serum to make a considered skincare routine feel complete.', benefits: 'Supports a soft, hydrated and comfortable skin feel.', usage: 'Smooth a few drops over clean skin before moisturiser.', ingredients: 'Ingredients available on product packaging.', availability: 'In Stock', featured: true },
  { id: '004', name: 'Giordani Gold Eau de Parfum', category: 'Fragrance', price: 28000, image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80', description: 'An elegant fragrance for moments that call for a little more presence.', benefits: 'A polished scent designed for everyday wear.', usage: 'Spritz lightly on pulse points.', ingredients: 'Ingredients available on product packaging.', availability: 'In Stock', featured: true },
  { id: '005', name: 'Love Nature Face Wash', category: 'Face Care', price: 8500, image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80', description: 'A simple cleansing step for a fresh start to your routine.', benefits: 'Cleanses without leaving skin feeling tight.', usage: 'Massage onto damp skin, then rinse thoroughly.', ingredients: 'Ingredients available on product packaging.', availability: 'Out of Stock', featured: false },
  { id: '006', name: 'Tender Care Protecting Balm', category: 'Skincare', price: 6500, image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=900&q=80', description: 'A small, versatile balm for dry-feeling areas that need extra care.', benefits: 'Helps comfort and soften dry-feeling skin.', usage: 'Apply a small amount wherever skin needs it.', ingredients: 'Ingredients available on product packaging.', availability: 'In Stock', featured: false }
];
function getProduct(id) { return products.find(product => product.id === id); }
function money(value) { return `₦${value.toLocaleString('en-NG')}`; }
