// Imported from Catalogue Q3 - UPDATED.pdf. Local images extracted from the catalogue.
const products = [
  {
    "id": "46319",
    "name": "Novage+ Proceuticals 10% Niacinamide Power Drops",
    "category": "Skincare",
    "price": 56790,
    "image": "images/catalogue/catalogue-0007.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": true
  },
  {
    "id": "47697",
    "name": "Milk & Honey Gold Nourishing Shampoo",
    "category": "Hair Care",
    "price": 21790,
    "image": "images/catalogue/catalogue-0014.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": true
  },
  {
    "id": "47698",
    "name": "Milk & Honey Gold Nourishing Conditioner",
    "category": "Hair Care",
    "price": 21790,
    "image": "images/catalogue/catalogue-0014.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": true
  },
  {
    "id": "46045",
    "name": "Giordani Gold Mister Giordani Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0018.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": true
  },
  {
    "id": "47513",
    "name": "Giordani Gold Miss Giordani Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0025.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": true
  },
  {
    "id": "49126",
    "name": "Optifresh Sensitive Toothpaste",
    "category": "Wellness",
    "price": 8490,
    "image": "images/catalogue/catalogue-0032.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": true
  },
  {
    "id": "49127",
    "name": "Optifresh Pro white Toothpaste",
    "category": "Wellness",
    "price": 8490,
    "image": "images/catalogue/catalogue-0032.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "49128",
    "name": "Optifresh Maximum Fresh Toothpaste",
    "category": "Wellness",
    "price": 8490,
    "image": "images/catalogue/catalogue-0032.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "49129",
    "name": "Optifresh Natural Oils Toothpaste",
    "category": "Wellness",
    "price": 8490,
    "image": "images/catalogue/catalogue-0032.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42751",
    "name": "Love Potion Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0036.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46047",
    "name": "Love Potion Cherry on Top Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0036.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44950",
    "name": "DUOLOGI Intense Repair Shampoo",
    "category": "Hair Care",
    "price": 27290,
    "image": "images/catalogue/catalogue-0058.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44951",
    "name": "DUOLOGI Anti-Flake Purifying Shampoo",
    "category": "Hair Care",
    "price": 27290,
    "image": "images/catalogue/catalogue-0058.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44960",
    "name": "DUOLOGI Rich Creme Conditioner",
    "category": "Hair Care",
    "price": 27290,
    "image": "images/catalogue/catalogue-0058.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44963",
    "name": "DUOLOGI Intense Repair Hair Mask",
    "category": "Hair Care",
    "price": 23490,
    "image": "images/catalogue/catalogue-0058.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44964",
    "name": "DUOLOGI Sealing Hair Serum",
    "category": "Hair Care",
    "price": 26390,
    "image": "images/catalogue/catalogue-0058.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41817",
    "name": "The body edition Anti-Cellulite Body Gel",
    "category": "Body Care",
    "price": 33290,
    "image": "images/catalogue/catalogue-0069.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41827",
    "name": "The body edition Anti- Stretch mark Body Concentrate",
    "category": "Body Care",
    "price": 33290,
    "image": "images/catalogue/catalogue-0069.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41283",
    "name": "Love Nature Nourishing Body, Face & Hair Oil with organic Avocado oil",
    "category": "Hair Care",
    "price": 17290,
    "image": "images/catalogue/catalogue-0076.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41029",
    "name": "Novage+ Refresh Gel Cleanser",
    "category": "Skincare",
    "price": 43890,
    "image": "images/catalogue/catalogue-0078.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41059",
    "name": "Novage+ Proceuticals Ultra Light UV-Age Day Shield + SPF 50",
    "category": "Skincare",
    "price": 43390,
    "image": "images/catalogue/catalogue-0079.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42255",
    "name": "Novage+ Intense Skin Recharge Overnight Mask",
    "category": "Skincare",
    "price": 45990,
    "image": "images/catalogue/catalogue-0079.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42256",
    "name": "Novage+ Intense Nourishment Facial Oil Capsules",
    "category": "Skincare",
    "price": 66690,
    "image": "images/catalogue/catalogue-0079.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42425",
    "name": "Novage+ Lift + Firm Eye Cream",
    "category": "Skincare",
    "price": 490904,
    "image": "images/catalogue/catalogue-0082.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41033",
    "name": "Novage+ Bright Intense Eye Cream",
    "category": "Skincare",
    "price": 490904,
    "image": "images/catalogue/catalogue-0082.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41035",
    "name": "Novage+ Wrinkle Smooth Serum",
    "category": "Skincare",
    "price": 681904,
    "image": "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=80",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41058",
    "name": "Novage+ Multi- Active Anti-Ageing Night Cream Rich",
    "category": "Skincare",
    "price": 549904,
    "image": "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=80",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41044",
    "name": "Novage+ Multi- Active Anti-Ageing Day Cream Light SPF 30",
    "category": "Skincare",
    "price": 549904,
    "image": "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=80",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41040",
    "name": "Novage+ Bright Intense Serum",
    "category": "Skincare",
    "price": 681904,
    "image": "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=80",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41037",
    "name": "Novage+ Lift + Firm Serum",
    "category": "Skincare",
    "price": 681904,
    "image": "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=80",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41075",
    "name": "Novage+ Restore Renewing Face Serum",
    "category": "Skincare",
    "price": 79490,
    "image": "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=80",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42610",
    "name": "Optimals Soothing Micellar Cleansing Water",
    "category": "Skincare",
    "price": 17490,
    "image": "images/catalogue/catalogue-0088.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42615",
    "name": "Optimals Purifying Clay Face Mask",
    "category": "Skincare",
    "price": 20590,
    "image": "images/catalogue/catalogue-0088.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45243",
    "name": "OPT Optimals Even Out Light Cream",
    "category": "Skincare",
    "price": 26190,
    "image": "images/catalogue/catalogue-0091.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45248",
    "name": "Opt Optimals Even Out Serum",
    "category": "Skincare",
    "price": 31890,
    "image": "images/catalogue/catalogue-0002.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45291",
    "name": "Opt Optimals Eye & Lip Contour Cream",
    "category": "Skincare",
    "price": 22490,
    "image": "images/catalogue/catalogue-0091.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45292",
    "name": "Opt Optimals Daily Glow Multi-Protector SPF50",
    "category": "Skincare",
    "price": 28990,
    "image": "images/catalogue/catalogue-0091.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46900",
    "name": "Opt Optimals Soft Creamy Cleanser",
    "category": "Skincare",
    "price": 17490,
    "image": "images/catalogue/catalogue-0091.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41675",
    "name": "Pure Skin Smoothing Face Scrub",
    "category": "Skincare",
    "price": 14490,
    "image": "images/catalogue/catalogue-0095.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41672",
    "name": "Pure Skin Clarifying Toning Solution",
    "category": "Skincare",
    "price": 15290,
    "image": "images/catalogue/catalogue-0095.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41673",
    "name": "Pure Skin Mattifying & Cooling Face Lotion",
    "category": "Skincare",
    "price": 15290,
    "image": "images/catalogue/catalogue-0095.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41674",
    "name": "Pure Skin 5 Minute Oil- control Clay Mask",
    "category": "Skincare",
    "price": 14490,
    "image": "images/catalogue/catalogue-0095.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41676",
    "name": "Pure Skin SOS Blemish Gel",
    "category": "Skincare",
    "price": 13490,
    "image": "images/catalogue/catalogue-0095.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "34843",
    "name": "Love Nature Purifying Toner with Organic Tea Tree & Lime",
    "category": "Skincare",
    "price": 14690,
    "image": "images/catalogue/catalogue-0101.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "34849",
    "name": "Love Nature Purifying Face Oil with Organic Tea Tree & Lime",
    "category": "Skincare",
    "price": 11290,
    "image": "images/catalogue/catalogue-0101.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "34845",
    "name": "Love Nature Mattifying Face Lotion with Organic Tea Tree & Lime",
    "category": "Skincare",
    "price": 14690,
    "image": "images/catalogue/catalogue-0101.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46072",
    "name": "Love Nature Hydrating Face Mask with Organic Aloe Vera & Pineapple",
    "category": "Skincare",
    "price": 14690,
    "image": "images/catalogue/catalogue-0109.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46070",
    "name": "Love Nature Hydrating Gel Cleanser with Organic Aloe Vera & Pineapple",
    "category": "Skincare",
    "price": 14690,
    "image": "images/catalogue/catalogue-0109.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47003",
    "name": "Love Nature Hydrating Toner with Organic Aloe Vera & Pineapple",
    "category": "Skincare",
    "price": 14690,
    "image": "images/catalogue/catalogue-0109.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46071",
    "name": "Love Nature Hydrating Face Cream with Organic Aloe Vera & Pineapple",
    "category": "Skincare",
    "price": 14690,
    "image": "images/catalogue/catalogue-0109.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41505",
    "name": "Love Nature Energising Body Lotion with Organic Mint & Raspberry",
    "category": "Body Care",
    "price": 34790,
    "image": "images/catalogue/catalogue-0111.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41490",
    "name": "Love Nature Nourishing Body Lotion with Organic Cacao Butter & Coconut Oil",
    "category": "Body Care",
    "price": 47790,
    "image": "images/catalogue/catalogue-0111.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42991",
    "name": "Love Nature Nourishing Body Cream with Organic Cacao Butter & Coconut Oil",
    "category": "Body Care",
    "price": 19790,
    "image": "images/catalogue/catalogue-0111.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47020",
    "name": "All Or Nothing Amplified Perfumed Body Cream",
    "category": "Fragrance",
    "price": 23990,
    "image": "images/catalogue/catalogue-0122.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47013",
    "name": "Love Potion Perfumed Body Cream",
    "category": "Fragrance",
    "price": 23990,
    "image": "images/catalogue/catalogue-0122.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47016",
    "name": "Divine Perfumed Body Cream",
    "category": "Fragrance",
    "price": 23990,
    "image": "images/catalogue/catalogue-0122.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47011",
    "name": "Giordani Gold Essenza Perfumed Body Cream",
    "category": "Fragrance",
    "price": 23990,
    "image": "images/catalogue/catalogue-0122.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "43907",
    "name": "Glow Essentials Body Lotion with Vitamins E & B3",
    "category": "Body Care",
    "price": 16590,
    "image": "images/catalogue/catalogue-0123.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46989",
    "name": "Tender Care Sweet Mandarin Multi- purpose Balm",
    "category": "Skincare",
    "price": 9490,
    "image": "images/catalogue/catalogue-0124.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "36151",
    "name": "Tender Care Blackcurrant Multi- purpose Balm",
    "category": "Skincare",
    "price": 9490,
    "image": "images/catalogue/catalogue-0124.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "12760",
    "name": "Tender Care Natural Multi-purpose Balm",
    "category": "Skincare",
    "price": 9490,
    "image": "images/catalogue/catalogue-0124.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "36152",
    "name": "Tender Care Raspberry Multi-purpose Balm",
    "category": "Skincare",
    "price": 9490,
    "image": "images/catalogue/catalogue-0124.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46968",
    "name": "Milk & Honey Gold Nourishing Hand & Body Cream",
    "category": "Body Care",
    "price": 22390,
    "image": "images/catalogue/catalogue-0131.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46969",
    "name": "Milk & Honey Gold Smoothing Sugar Scrub",
    "category": "Skincare",
    "price": 23990,
    "image": "images/catalogue/catalogue-0131.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47224",
    "name": "Milk & Honey Gold Moisturising Hand Cream",
    "category": "Body Care",
    "price": 11390,
    "image": "images/catalogue/catalogue-0131.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45139",
    "name": "Wellosophy Smooth & Balance Gel-Serum",
    "category": "Wellness",
    "price": 48990,
    "image": "images/catalogue/catalogue-0137.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45138",
    "name": "Wellosophy Plump & Balance Face Cream",
    "category": "Wellness",
    "price": 34990,
    "image": "images/catalogue/catalogue-0137.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45149",
    "name": "Wellosophy Calm & Balance Cleanser",
    "category": "Wellness",
    "price": 23490,
    "image": "images/catalogue/catalogue-0137.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45273",
    "name": "Wellosophy Skin, Hair & Nail NutriComplex 60 tablets. 2 a day",
    "category": "Hair Care",
    "price": 49990,
    "image": "images/catalogue/catalogue-0138.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45306",
    "name": "Wellosophy Meal Replacement for Weight Control Vanilla Flavour 25g per serving. 21 servings",
    "category": "Wellness",
    "price": 124990,
    "image": "images/catalogue/catalogue-0143.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38838",
    "name": "Wellosophy Wellness Pack Woman 21 sachets. 1 sachet daily",
    "category": "Wellness",
    "price": 764903,
    "image": "images/catalogue/catalogue-0153.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45307",
    "name": "Wellosophy Meal Replacement for Weight Control Chocolate Flavour 25g per serving. 21 servings",
    "category": "Wellness",
    "price": 124990,
    "image": "images/catalogue/catalogue-0143.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38559",
    "name": "Wellosophy Multivitamin & Mineral Woman 60 tablets. 1 tablet a day",
    "category": "Wellness",
    "price": 49990,
    "image": "images/catalogue/catalogue-0150.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38558",
    "name": "Wellosophy Multivitamin & Mineral Man 60 tablets. 1 tablet a day",
    "category": "Wellness",
    "price": 49990,
    "image": "images/catalogue/catalogue-0150.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45309",
    "name": "Wellosophy Marine Calcium & Vitamin D 30 tablets. 1-2 a day",
    "category": "Wellness",
    "price": 42490,
    "image": "images/catalogue/catalogue-0152.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38556",
    "name": "Wellosophy Omega 3 60 capsules. 2 capsules a day",
    "category": "Wellness",
    "price": 39990,
    "image": "images/catalogue/catalogue-0002.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38557",
    "name": "Wellosophy Astaxanthin & Bilberry Extract 30 capsules. 1-2 capsules a day",
    "category": "Wellness",
    "price": 50990,
    "image": "images/catalogue/catalogue-0152.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38836",
    "name": "Wellosophy Wellness Pack Man 21 sachets. 1 sachet daily",
    "category": "Wellness",
    "price": 76490,
    "image": "images/catalogue/catalogue-0153.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46801",
    "name": "Divine Dark Velvet Eau De Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0002.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38497",
    "name": "Divine Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0158.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44315",
    "name": "Infinita My Sunshine Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0159.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "35653",
    "name": "Infinita Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0159.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "40809",
    "name": "Whispers Of Me Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0164.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42514",
    "name": "Volare Eau de Parfum",
    "category": "Fragrance",
    "price": 43990,
    "image": "images/catalogue/catalogue-0164.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44288",
    "name": "OH! SWEET DULCE DE LECHE Eau de Toilette",
    "category": "Fragrance",
    "price": 367905,
    "image": "images/catalogue/catalogue-0164.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "35681",
    "name": "Amber Elixir Mystery Eau de Parfum",
    "category": "Fragrance",
    "price": 59990,
    "image": "images/catalogue/catalogue-0176.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "35679",
    "name": "All or Nothing Parfum",
    "category": "Fragrance",
    "price": 99990,
    "image": "images/catalogue/catalogue-0179.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46060",
    "name": "All or Nothing Amplified Parfum",
    "category": "Fragrance",
    "price": 99990,
    "image": "images/catalogue/catalogue-0179.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47511",
    "name": "Giordani Gold Essenza Parfum",
    "category": "Fragrance",
    "price": 89990,
    "image": "images/catalogue/catalogue-0180.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "40683",
    "name": "Giordani Gold Essenza Supreme Parfum",
    "category": "Fragrance",
    "price": 89990,
    "image": "images/catalogue/catalogue-0180.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45967",
    "name": "Giordani Gold Essenza Man Elixir Parfum",
    "category": "Fragrance",
    "price": 89990,
    "image": "images/catalogue/catalogue-0180.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42806",
    "name": "Giordani Gold Essenza Perfumed Body Spray",
    "category": "Fragrance",
    "price": 14490,
    "image": "images/catalogue/catalogue-0180.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38531",
    "name": "Giordani Gold Woman Eau de Parfum",
    "category": "Fragrance",
    "price": 59990,
    "image": "images/catalogue/catalogue-0196.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38538",
    "name": "Giordani Gold Man Eau de Parfum",
    "category": "Fragrance",
    "price": 59990,
    "image": "images/catalogue/catalogue-0196.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47502",
    "name": "Giordani Gold Mister Giordani Aqua Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0200.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47514",
    "name": "Giordani Gold Miss Giordani Floral Eau de Parfum",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0200.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46792",
    "name": "Eclat Femme Weekend Riviera Eau de Toilette",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0218.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46795",
    "name": "Eclat Homme Weekend Azur Eau de Toilette",
    "category": "Fragrance",
    "price": 54990,
    "image": "images/catalogue/catalogue-0218.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "35649",
    "name": "Eclat Amour Eau de Toilette",
    "category": "Fragrance",
    "price": 41990,
    "image": "images/catalogue/catalogue-0218.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "35651",
    "name": "Eclat Toujours Eau de Toilette",
    "category": "Fragrance",
    "price": 41990,
    "image": "images/catalogue/catalogue-0218.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38552",
    "name": "Greater Eau de Toilette for him",
    "category": "Fragrance",
    "price": 48990,
    "image": "images/catalogue/catalogue-0234.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "43118",
    "name": "Greater Eau de Toilette for her",
    "category": "Fragrance",
    "price": 48990,
    "image": "images/catalogue/catalogue-0234.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46056",
    "name": "Scope Time Loop Eau de Toilette",
    "category": "Fragrance",
    "price": 48990,
    "image": "images/catalogue/catalogue-0238.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46057",
    "name": "Scope Earth Wonder Eau de Toilette",
    "category": "Fragrance",
    "price": 48990,
    "image": "images/catalogue/catalogue-0238.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "40667",
    "name": "Glacier Extreme Eau De Toilette",
    "category": "Fragrance",
    "price": 36790,
    "image": "images/catalogue/catalogue-0249.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "42816",
    "name": "Glacier Rock Eau de Toilette",
    "category": "Fragrance",
    "price": 36790,
    "image": "images/catalogue/catalogue-0249.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "38527",
    "name": "Ascendant Intense Eau de Parfum",
    "category": "Fragrance",
    "price": 59990,
    "image": "images/catalogue/catalogue-0253.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "48671",
    "name": "Signature Man Eau de Toilette",
    "category": "Fragrance",
    "price": 59990,
    "image": "images/catalogue/catalogue-0253.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "30468",
    "name": "Be the Legend Eau de Toilette",
    "category": "Fragrance",
    "price": 41990,
    "image": "images/catalogue/catalogue-0254.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46044",
    "name": "Men's Collection Agave Power Eau De Toilette",
    "category": "Fragrance",
    "price": 43990,
    "image": "images/catalogue/catalogue-0254.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "45357",
    "name": "Possess Absolute Man Eau de Parfum",
    "category": "Fragrance",
    "price": 71990,
    "image": "images/catalogue/catalogue-0258.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46966",
    "name": "Feminelle Moisturising Intimate Cleansing Cream with Hyaluronic Acid and Peach Extract",
    "category": "Wellness",
    "price": 149906,
    "image": "images/catalogue/catalogue-0265.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46964",
    "name": "Feminelle Gentle Intimate Wash with Cotton Extract",
    "category": "Wellness",
    "price": 14990,
    "image": "images/catalogue/catalogue-0266.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46367",
    "name": "Feminelle Smoothing Shaving Gel with Aloe Vera",
    "category": "Wellness",
    "price": 16790,
    "image": "images/catalogue/catalogue-0266.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46965",
    "name": "Feminelle Soothing Intimate Wash with Aloe Vera",
    "category": "Wellness",
    "price": 149906,
    "image": "images/catalogue/catalogue-0266.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47762",
    "name": "Giordani Gold Mister Giordani Perfumed Anti-perspirant Roll-On Deodorant",
    "category": "Fragrance",
    "price": 9190,
    "image": "images/catalogue/catalogue-0267.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47761",
    "name": "Possess Perfumed Anti-perspirant Roll-On Deodorant",
    "category": "Fragrance",
    "price": 9190,
    "image": "images/catalogue/catalogue-0267.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47760",
    "name": "Giordani Gold Woman Perfumed Anti-perspirant Roll- On Deodorant",
    "category": "Fragrance",
    "price": 9190,
    "image": "images/catalogue/catalogue-0267.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47763",
    "name": "Glacier Perfumed Anti-perspirant Roll-On Deodorant",
    "category": "Fragrance",
    "price": 9190,
    "image": "images/catalogue/catalogue-0267.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47759",
    "name": "Giordani Gold Miss Giordani Perfumed Anti-perspirant Roll-On Deodorant",
    "category": "Fragrance",
    "price": 9190,
    "image": "images/catalogue/catalogue-0267.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "33142",
    "name": "Activelle Extreme Anti- perspirant Deodorant",
    "category": "Fragrance",
    "price": 7990,
    "image": "images/catalogue/catalogue-0268.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41303",
    "name": "Activelle Invisible Fresh anti- perspirant deodorant",
    "category": "Fragrance",
    "price": 7990,
    "image": "images/catalogue/catalogue-0268.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "43926",
    "name": "Activelle Even Tone anti- perspirant deodorant",
    "category": "Fragrance",
    "price": 7990,
    "image": "images/catalogue/catalogue-0268.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46381",
    "name": "Activelle Power Move Anti- perspirant Deodorant",
    "category": "Fragrance",
    "price": 7990,
    "image": "images/catalogue/catalogue-0268.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41308",
    "name": "Love Nature Hot Oil For Dry Hair with Organic Wheat & Coconut",
    "category": "Hair Care",
    "price": 4590,
    "image": "images/catalogue/catalogue-0271.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41568",
    "name": "Love Nature Nourishing Hair Oil Coconut Oil",
    "category": "Hair Care",
    "price": 14990,
    "image": "images/catalogue/catalogue-0271.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41295",
    "name": "Love Nature Conditioner For Dry Hair with Organic Wheat & Coconut",
    "category": "Hair Care",
    "price": 13790,
    "image": "images/catalogue/catalogue-0271.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "43661",
    "name": "Love Nature Strengthening Hair Smoothie Mask with Organic Banana",
    "category": "Hair Care",
    "price": 5290,
    "image": "images/catalogue/catalogue-0276.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41362",
    "name": "Love Nature 2-in-1 Shampoo For All Hair Types with Organic Avocado Oil & Chamomile",
    "category": "Hair Care",
    "price": 25990,
    "image": "images/catalogue/catalogue-0276.png",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46376",
    "name": "Feet Up Everyday / Refreshing Foot Spray",
    "category": "Body Care",
    "price": 299904,
    "image": "images/catalogue/catalogue-0297.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46375",
    "name": "Feet Up Everyday / Softening Foot Cream",
    "category": "Body Care",
    "price": 184904,
    "image": "images/catalogue/catalogue-0297.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46149",
    "name": "North For Men Subzero 2-in-1 Moisturising Gel",
    "category": "Skincare",
    "price": 8990,
    "image": "images/catalogue/catalogue-0301.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46632",
    "name": "North For Men Subzero 2-in-1 Shaving & Cleansing Foam",
    "category": "Skincare",
    "price": 22990,
    "image": "images/catalogue/catalogue-0301.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46633",
    "name": "North For Men Subzero Deodorant Roll-On",
    "category": "Fragrance",
    "price": 7990,
    "image": "images/catalogue/catalogue-0301.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46549",
    "name": "THE ONE False Lashes Salon Lift 360 Bendable Mascara - Black",
    "category": "Makeup",
    "price": 19990,
    "image": "images/catalogue/catalogue-0306.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "46438",
    "name": "Baked Terracotta 46443 Marvellous Mocha 46446 Deep Berry 46447 Smart Red 46449 Cherry Plum THE ONE Smart Sync Lipstick",
    "category": "Makeup",
    "price": 19790,
    "image": "images/catalogue/catalogue-0311.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "41338",
    "name": "Love Nature Nourishing Hand Cream with Organic Coconut Oil",
    "category": "Body Care",
    "price": 8490,
    "image": "images/catalogue/catalogue-0353.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "44280",
    "name": "Love Nature Caring Hand Cream with Organic Avocado Oil",
    "category": "Body Care",
    "price": 8490,
    "image": "images/catalogue/catalogue-0353.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  },
  {
    "id": "47202",
    "name": "Love Nature Protecting Hand & Nail Cream with Organic Passion Fruit",
    "category": "Body Care",
    "price": 8490,
    "image": "images/catalogue/catalogue-0353.jpg",
    "description": "Product details from the Q3 catalogue.",
    "benefits": "See product packaging for current product information.",
    "usage": "Use according to the instructions on the product packaging.",
    "ingredients": "See product packaging.",
    "availability": "In Stock",
    "featured": false
  }
];
function getProduct(id) { return products.find(product => product.id === id); }
function money(value) { return `&#8358;${value.toLocaleString('en-NG')}`; }
